# Generated by Django 3.1.5 on 2021-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='row',
            name='order',
            field=models.FloatField(default=10000),
        ),
    ]
