# Generated by Django 3.1.5 on 2021-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0002_auto_20210127_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cell',
            name='comment',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalcell',
            name='colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcell',
            name='comment',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
