# Generated by Django 3.1.5 on 2021-01-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0003_auto_20210127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='colour',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='comment',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='text',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcell',
            name='colour',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcell',
            name='comment',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcell',
            name='text',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
