# Generated by Django 3.1.5 on 2021-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0004_auto_20210127_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='order',
            field=models.FloatField(),
        ),
    ]
