# Generated by Django 3.1.5 on 2021-01-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0006_auto_20210127_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'Dictionaries'},
        ),
    ]
