# Generated by Django 3.1.5 on 2021-01-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0008_auto_20210127_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_hub.dictionary'),
        ),
    ]
