# Generated by Django 3.1.5 on 2021-01-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0009_auto_20210127_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='name_display',
            field=models.CharField(default='', max_length=200),
        ),
    ]
