# Generated by Django 3.1.5 on 2021-01-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0010_dictionary_name_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcell',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
