# Generated by Django 3.1.5 on 2021-01-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0013_auto_20210128_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup_hub.category'),
        ),
    ]
